name: riverfire
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cloud_firestore: 0.16.0
  dartx: any
  dartz: any
  firebase_auth: any
  firebase_core: any
  flutter:
    sdk: flutter
  freezed_annotation: any
  google_sign_in: any
  json_annotation: any
  kt_dart: any
  riverpod: any
  rxdart: any

dev_dependencies:
  abide: any
  build_runner: any
  derry: any
  freezed: any
  json_serializable_immutable_collections: any
  test: any

scripts:
  gen: flutter packages run build_runner build --delete-conflicting-outputs
  genw: flutter packages run build_runner watch --delete-conflicting-outputs
