name: riverfire
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.0
  dartz: ^0.10.0
  firebase_auth: any
  firebase_core: any
  flutter:
    sdk: flutter
  freezed_annotation: ^1.0.0
  google_sign_in: any
  json_annotation: ^4.0.0
  riverpod: ^1.0.0
  rxdart: any

dev_dependencies:
  build_runner: any
  freezed: ^1.0.0
  json_serializable: any
  test: any

scripts:
  gen: flutter packages run build_runner build --delete-conflicting-outputs
  genw: flutter packages run build_runner watch --delete-conflicting-outputs
